apiVersion: v1
kind: Pod
metadata:
  name: calc-temp-pod
  labels:
    name: web
spec:
  containers:
  - name: web
    image: amisaka/conversao-temperatura:latest
    resources:
      limits:
        memory: "128Mi"
        cpu: "500m"
    ports:
      - containerPort: 80

 
